services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите имя вашего Dockerfile, если он называется не просто Dockerfile
    environment:
      # Переменные окружения из `.env`
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Приложение будет доступно на localhost:8000
    depends_on:
      - db
    command: ["sh", "-c", "poetry run alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Подключение к базе данных

  test:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите имя вашего Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    command: ["pytest", "--cov=src", "--cov-report=term-missing"]
    depends_on:
      - db

volumes:
  postgres_data:
